import Navbar from "@/components/nav-bar";
import { ThemeProvider } from "@/components/provider/theme-provider";
import Sidebar from "@/components/sidebar";
import { Toaster } from "@/components/ui/toaster";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProvider attribute="class" defaultTheme="light" enableSystem storageKey="dashboard-theme">
          <Navbar />
          <div className="flex">
            <div className=" hidden md:block h-screen w-[300px]">
              <Sidebar />
            </div>
            <div className=" p-5 w-full md:max-w-[1140px]">{children}</div>
          </div>
          <Toaster />
        </ThemeProvider>
      </body>
    </html>
  );
}
